//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace TTRPGConverter.Core.Models.Pathbuilder
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Extracted custom_feat definition
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json
    {

        /// <summary>
        /// Database identifier
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("databaseID")]
        public int DatabaseID { get; set; } = default!;

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d+$")]
        public string Timestamp { get; set; } = default!;

        /// <summary>
        /// Unique feat ID (UUID)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Feat name
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Required level for feat
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("level")]
        [System.ComponentModel.DataAnnotations.Range(1, 20)]
        public int Level { get; set; } = default!;

        /// <summary>
        /// Feat traits (comma-separated)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("traits")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Traits { get; set; } = default!;

        /// <summary>
        /// Feat prerequisites
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("prerequisites")]
        public string? Prerequisites { get; set; } = default!;

        /// <summary>
        /// Usage frequency
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("frequency")]
        public string? Frequency { get; set; } = default!;

        /// <summary>
        /// Trigger condition
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("trigger")]
        public string? Trigger { get; set; } = default!;

        /// <summary>
        /// Feat description and effects
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Description { get; set; } = default!;

        /// <summary>
        /// Source book/pack
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("src")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Src { get; set; } = default!;

        /// <summary>
        /// Action type (empty=passive, 1-3=actions, R=reaction, F=free)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("actionType")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public JsonActionType? ActionType { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum JsonActionType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"")]
        Empty = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"1")]
        _1 = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"2")]
        _2 = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"3")]
        _3 = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"R")]
        R = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"F")]
        F = 5,


    }
}