//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace TTRPGConverter.Core.Models.Pathbuilder
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Extracted custom_ancestry definition
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json
    {

        /// <summary>
        /// Database identifier
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("databaseID")]
        public int DatabaseID { get; set; } = default!;

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d+$")]
        public string Timestamp { get; set; } = default!;

        /// <summary>
        /// Unique ancestry ID (UUID)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Ancestry name
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Base hit points
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("hp")]
        [System.ComponentModel.DataAnnotations.Range(4, 12)]
        public int Hp { get; set; } = default!;

        /// <summary>
        /// Size category: 1=Small, 2=Medium, 3=Large, 4=Huge
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("size")]
        public JsonSize Size { get; set; } = default!;

        /// <summary>
        /// Base speed in feet
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("speed")]
        [System.ComponentModel.DataAnnotations.Range(5, int.MaxValue)]
        public int Speed { get; set; } = default!;

        /// <summary>
        /// Ancestry traits (comma-separated)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("traits")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Traits { get; set; } = default!;

        /// <summary>
        /// First ability boost reference
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("boost_ref_1")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public JsonBoost_ref_1? Boost_ref_1 { get; set; } = default!;

        /// <summary>
        /// Second ability boost reference
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("boost_ref_2")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public JsonBoost_ref_2? Boost_ref_2 { get; set; } = default!;

        /// <summary>
        /// Ability flaw reference (empty if none)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("flaw_ref")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public JsonFlaw_ref? Flaw_ref { get; set; } = default!;

        /// <summary>
        /// Starting languages
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("languages")]
        public System.Collections.Generic.List<string>? Languages { get; set; } = default!;

        /// <summary>
        /// Special senses
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("senses")]
        public System.Collections.Generic.List<string>? Senses { get; set; } = default!;

        /// <summary>
        /// Ancestry description
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Description { get; set; } = default!;

        /// <summary>
        /// Source book/pack
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("src")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Src { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum JsonSize
    {

        _1 = 1,


        _2 = 2,


        _3 = 3,


        _4 = 4,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum JsonBoost_ref_1
    {

        [System.Runtime.Serialization.EnumMember(Value = @"0")]
        _0 = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"1")]
        _1 = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"2")]
        _2 = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"3")]
        _3 = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"4")]
        _4 = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"5")]
        _5 = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"FREE")]
        FREE = 6,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum JsonBoost_ref_2
    {

        [System.Runtime.Serialization.EnumMember(Value = @"0")]
        _0 = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"1")]
        _1 = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"2")]
        _2 = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"3")]
        _3 = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"4")]
        _4 = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"5")]
        _5 = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"FREE")]
        FREE = 6,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum JsonFlaw_ref
    {

        [System.Runtime.Serialization.EnumMember(Value = @"0")]
        _0 = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"1")]
        _1 = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"2")]
        _2 = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"3")]
        _3 = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"4")]
        _4 = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"5")]
        _5 = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"")]
        Empty = 6,


    }
}