# Rust Formatting Configuration
# Based on Rust best practices and team consistency standards
# Using only stable rustfmt features

# Edition and basic settings
edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Max"

# Import organization (stable features only)
reorder_imports = true
reorder_modules = true

# Code style preferences (stable features only)
remove_nested_parens = true

# Function and struct formatting (stable features only)
fn_params_layout = "Tall"  # Updated from deprecated fn_args_layout

# Advanced formatting (stable features only)
use_field_init_shorthand = true
use_try_shorthand = true

# Stable formatting options
chain_width = 60
single_line_if_else_max_width = 50

# Removed unstable features that were causing warnings:
# - wrap_comments
# - format_code_in_doc_comments  
# - comment_width
# - normalize_comments
# - normalize_doc_attributes
# - format_strings
# - format_macro_matchers
# - format_macro_bodies
# - struct_lit_single_line
# - fn_single_line
# - where_single_line
# - imports_granularity
# - group_imports
# - brace_style
# - control_brace_style
# - condense_wildcard_suffixes
