//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace TTRPGConverter.Core.Models.Foundry.Common
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Ability score with modifiers
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Range(1D, 30D)]
        public double? Value { get; set; } = default!;

        /// <summary>
        /// Proficiency multiplier (0, 0.5, 1, 2)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("proficient")]
        public double? Proficient { get; set; } = default!;

        /// <summary>
        /// Additional bonus
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("bonus")]
        public double? Bonus { get; set; } = default!;

        /// <summary>
        /// Calculated modifier
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mod")]
        public double? Mod { get; set; } = default!;

        /// <summary>
        /// Calculated save bonus
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("save")]
        public double? Save { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}