//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace TTRPGConverter.Core.Models.Foundry.Common
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Light emission properties
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json
    {

        /// <summary>
        /// Bright light radius
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("bright")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? Bright { get; set; } = default!;

        /// <summary>
        /// Dim light radius
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dim")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? Dim { get; set; } = default!;

        /// <summary>
        /// Light angle in degrees
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("angle")]
        [System.ComponentModel.DataAnnotations.Range(0D, 360D)]
        public double? Angle { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("color")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^#[0-9a-fA-F]{6}$")]
        public string? Color { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("animation")]
        public Animation? Animation { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Animation
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public AnimationType? Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("speed")]
        [System.ComponentModel.DataAnnotations.Range(1D, 10D)]
        public double? Speed { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("intensity")]
        [System.ComponentModel.DataAnnotations.Range(1D, 10D)]
        public double? Intensity { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum AnimationType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"none")]
        None = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"pulse")]
        Pulse = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"chroma")]
        Chroma = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"wave")]
        Wave = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"fog")]
        Fog = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"sunburst")]
        Sunburst = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"dome")]
        Dome = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"emanation")]
        Emanation = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"hexa")]
        Hexa = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"ghost")]
        Ghost = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"energy")]
        Energy = 10,


        [System.Runtime.Serialization.EnumMember(Value = @"roiling")]
        Roiling = 11,


        [System.Runtime.Serialization.EnumMember(Value = @"hole")]
        Hole = 12,


    }
}