[package]
name = "ttrpg-pathbuilder-pf2e"
version = "0.1.0"
edition = "2021"
description = "Pathbuilder Pathfinder 2e schemas and bidirectional mappings for TTRPG Converter"

[features]
default = ["schemas", "mappings"]
schemas = []
mappings = ["schemas"]
schemas-only = ["schemas"]
minimal = []

[dependencies]
ttrpg-types = { path = "../../core/ttrpg-types" }
thiserror = "1.0"
ttrpg-traits = { path = "../../core/ttrpg-traits" }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
chrono = { workspace = true }
regress = { workspace = true }
o2o = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[build-dependencies]
ttrpg-build-utils = { path = "../../core/ttrpg-build-utils" }
