//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace TTRPGConverter.Core.Models.Foundry.Systems.Dnd5e
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Document ownership permissions by user role
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Ownership
    {

        /// <summary>
        /// Default permission level (0=None, 1=Limited, 2=Observer, 3=Owner)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("default")]
        public OwnershipDefault? Default { get; set; } = default!;

    }

    /// <summary>
    /// Document creation/modification metadata
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DocumentStats
    {

        /// <summary>
        /// Game system ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("systemId")]
        public string? SystemId { get; set; } = default!;

        /// <summary>
        /// Game system version
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("systemVersion")]
        public string? SystemVersion { get; set; } = default!;

        /// <summary>
        /// Foundry core version
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("coreVersion")]
        public string? CoreVersion { get; set; } = default!;

        /// <summary>
        /// Creation timestamp (Unix milliseconds)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("createdTime")]
        public double? CreatedTime { get; set; } = default!;

        /// <summary>
        /// Last modification timestamp (Unix milliseconds)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("modifiedTime")]
        public double? ModifiedTime { get; set; } = default!;

        /// <summary>
        /// User ID who last modified
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("lastModifiedBy")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-zA-Z0-9]{16}$")]
        public string? LastModifiedBy { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Common properties shared by all Foundry VTT documents
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BaseDocument
    {

        /// <summary>
        /// Unique 16-character document ID
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("_id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-zA-Z0-9]{16}$")]
        public string _id { get; set; } = default!;

        /// <summary>
        /// Document name
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Parent folder ID, null if in root
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("folder")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-zA-Z0-9]{16}$")]
        public string? Folder { get; set; } = default!;

        /// <summary>
        /// Sort order for display
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sort")]
        public double? Sort { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("ownership")]
        public Ownership? Ownership { get; set; } = default!;

        /// <summary>
        /// Module/system-specific flags
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("flags")]
        public object? Flags { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("_stats")]
        public DocumentStats? _stats { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Ability_score
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Range(0, 30)]
        public int Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("proficient")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? Proficient { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("bonuses")]
        public Bonuses? Bonuses { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Resource
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("min")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Min { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("max")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Max { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("temp")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Temp { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tempmax")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Tempmax { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Currency
    {

        [System.Text.Json.Serialization.JsonPropertyName("pp")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Pp { get; set; } = 0;

        [System.Text.Json.Serialization.JsonPropertyName("gp")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Gp { get; set; } = 0;

        [System.Text.Json.Serialization.JsonPropertyName("ep")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Ep { get; set; } = 0;

        [System.Text.Json.Serialization.JsonPropertyName("sp")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Sp { get; set; } = 0;

        [System.Text.Json.Serialization.JsonPropertyName("cp")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int? Cp { get; set; } = 0;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// D&amp;D 5e spell slot with current/max values
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class SpellSlot
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("max")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? Max { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("override")]
        public double? Override { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Schema for Foundry VTT D&amp;D 5e actor documents
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json : BaseDocument
    {

        /// <summary>
        /// DND5e actor type
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public JsonType Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("img")]
        public System.Uri? Img { get; set; } = default!;

        /// <summary>
        /// DND5e-specific actor data
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("system")]
        [System.ComponentModel.DataAnnotations.Required]
        public System System { get; set; } = new System();

        /// <summary>
        /// Owned items
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.List<string>? Items { get; set; } = default!;

        /// <summary>
        /// Active effects
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("effects")]
        public System.Collections.Generic.List<string>? Effects { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum OwnershipDefault
    {

        _0 = 0,


        _1 = 1,


        _2 = 2,


        _3 = 3,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Bonuses
    {

        [System.Text.Json.Serialization.JsonPropertyName("check")]
        public string? Check { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("save")]
        public string? Save { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum JsonType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"character")]
        Character = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"npc")]
        Npc = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"vehicle")]
        Vehicle = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"group")]
        Group = 3,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class System
    {

        [System.Text.Json.Serialization.JsonPropertyName("abilities")]
        public Abilities? Abilities { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("attributes")]
        public Attributes? Attributes { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("details")]
        public Details? Details { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("currency")]
        public Currency? Currency { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spells")]
        public Spells? Spells { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Abilities
    {

        [System.Text.Json.Serialization.JsonPropertyName("str")]
        public Ability_score? Str { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("dex")]
        public Ability_score? Dex { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("con")]
        public Ability_score? Con { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("int")]
        public Ability_score? Int { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("wis")]
        public Ability_score? Wis { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("cha")]
        public Ability_score? Cha { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Attributes
    {

        [System.Text.Json.Serialization.JsonPropertyName("hp")]
        public Resource? Hp { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("ac")]
        public Ac? Ac { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("init")]
        public Init? Init { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("speed")]
        public Speed? Speed { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Details
    {

        [System.Text.Json.Serialization.JsonPropertyName("biography")]
        public Biography? Biography { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("alignment")]
        public string? Alignment { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("race")]
        public string? Race { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("background")]
        public string? Background { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("class")]
        public string? Class { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("level")]
        [System.ComponentModel.DataAnnotations.Range(1D, 20D)]
        public double? Level { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("xp")]
        public Xp? Xp { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Spells
    {

        [System.Text.Json.Serialization.JsonPropertyName("spell1")]
        public SpellSlot? Spell1 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell2")]
        public SpellSlot? Spell2 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell3")]
        public SpellSlot? Spell3 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell4")]
        public SpellSlot? Spell4 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell5")]
        public SpellSlot? Spell5 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell6")]
        public SpellSlot? Spell6 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell7")]
        public SpellSlot? Spell7 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell8")]
        public SpellSlot? Spell8 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("spell9")]
        public SpellSlot? Spell9 { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("pact")]
        public SpellSlot? Pact { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Ac
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public double? Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("min")]
        public double? Min { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("calc")]
        public string? Calc { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("formula")]
        public string? Formula { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Init
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public double? Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("bonus")]
        public double? Bonus { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Speed
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public double? Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("special")]
        public string? Special { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Biography
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public string? Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("public")]
        public string? Public { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.4.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Xp
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public double? Value { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("min")]
        public double? Min { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("max")]
        public double? Max { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}